
services:
  nord_java:
    container_name: nord_java
    image: nord_java:1.0
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db_mysql

    environment:
      MYSQL_HOST: db_mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    networks:
      - spring_mysql

  db_mysql:
    image: mysql:latest
    container_name: db_mysql
    volumes:
      - mysql_dados:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Nord
      MYSQL_USER: CrashDocker
      MYSQL_PASSWORD: CrashDocker
    ports:
      - "3307:3306"
    networks:
      - spring_mysql

volumes:
  mysql_dados: {}
networks:
  spring_mysql:
    driver: bridge