upstream backend{
  server nord_nord_java:8080;
  

}
server {
  listen 80;
  location /registrar {
    proxy_pass http://backend/Nord/Registrar;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /login {
    proxy_pass http://backend/Nord/Login;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /deletar {
    proxy_pass http://backend/Nord/Deletarconta;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /mudarsenha {
    proxy_pass http://backend/Nord/Mudarsenha;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

}
